<?
$PERM["index[bak.01].php"]["7"]="W";
$PERM["index-old.php"]["7"]="W";
$PERM["[DEL]about"]["7"]="W";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>